### PR TITLE
Update canvg JS links

### PR DESCRIPTION
**Pull request by tjvr**
Now that [Google Code has shut down](http://google-opensource.blogspot.co.uk/2015/03/farewell-to-google-code.html) we need a better place to pull these from.

### CODE REVIEW

**Comment by sfederici** [comment]
It would be great having everything working again :)

**Comment by tjvr** [comment]
BTW @nathan, here's the justification for the new links: <https://github.com/gabelerner/canvg#usage>

**Comment by CosmicWebServices** [comment]
Also this is already a fork: #388

**Comment by tjvr** [comment]
Closing. Thanks for fixing this, @nathan! :)

**Pull request closed without merging**
