### PR TITLE
Add any key

### LINKED ISSUE #503: Hacker Typer
Much less responsive than in Scratch.

http://scratch.mit.edu/projects/72232520/
http://phosphorus.github.io/#72232520
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36

### PR DESCRIPTION
**Pull request by tjvr**
Fixes #503, #565, #498

### CODE REVIEW

**Comment by nathan** [comment]
There's a much faster way to implement this.

**Comment by nathan** [comment]
Also this doesn't trigger hats in the right order.

**Comment by tjvr** [comment]
> There's a much faster way to implement this.

I thought about counting the number of keys which were down, but a) that would fail if the window was blurred and b) it's not how you did it in scratch-flash. Clearly I guessed wrong! :P

**Comment by nathan** [comment]
> a) that would fail if the window was blurred

If by "fail" you mean "continue to report that a key is pressed", your solution does that too. If you mean "forever become offset by 1", that's why my code checks the state for that individual key before in/decrementing.

Generally for scratch-flash I did the obviously correct thing and for phosphorus I do the non-obvious error-prone faster thing and try not to make any errors :P

**Comment by tjvr** [comment]
> If you mean "forever become offset by 1", that's why my code checks the state for that individual key before in/decrementing.

Yes, that's what I meant. You're very clever.

**Pull request closed without merging**
