### PR TITLE
Truncate continuations at first unconditional return

### LINKED ISSUE #211: Trim generated code after return statements
This will substantially decrease the size of the JS output, which should speed up parsing/compiling time.

### PR DESCRIPTION
**Pull request by nathan**
Close #211

### CODE REVIEW

**Comment by nathan** [comment]
Fails #140130952

**Comment by nathan** [comment]
(not anymore)

**Comment by nathan** [comment]
I worry about generating code that ends in `…return;`, like `var f = 1 + something_return;`

**Comment by tjvr** [comment]
Can't you just look for `\nreturn;` then? :P

**Comment by nathan** [comment]
There are some places that have `{return;}`, and technically it's possible to generate pathological code like

```window.
return;
```

(although we don't, and probably won't ever, do this)

Unfortunately, that doesn't catch indented return statements.

**Pull request merged**
