### PR TITLE
Add loadSB2Object for loading `zip` object directly from tosh

### PR DESCRIPTION
**Pull request by tjvr**
Took me ages to work out how `Request`/`CompositeRequest` work, but I think this is roughly what I want!

This way, I can construct a `zip` object like so:

``` javascript
    var zip = new JSZip();
    zip.file('project.json', JSON.stringify(p));
    zip.file('0.png', costume1.textFile);
    // ...
```

and then hand it straight to Phosphorus, avoiding the unnecessary `zip.generate()` step:

``` javascript
  var request = P.IO.loadSB2Object(zip);
  player.loadProject(request, function(stage) {
    // ...
```

Feedback on the name `loadSB2Object` is welcome.

### CODE REVIEW

**Comment by tjvr** [comment]
On second thought: this doesn't always work, for reasons I don't understand :(

**Comment by tjvr** [comment]
It looks like I have to add the following to my `player.js`:
```
    if (request.isDone) {
      request.onload(request.getResult());
    }
```
...otherwise onload() doesn't get called.

**Comment by nathan** [comment]
Does it work for you if I just overload `loadSB2Project` like this?

```js
IO.zip = Object.prototype.toString.call(ab) === '[object ArrayBuffer]' ? new JSZip(ab) : ab;
```

Then you can just pass the zip into `loadSB2Project`.

**Comment by tjvr** [comment]
That sounds great! :)

**Comment by nathan** [comment]
Cool. Sorry it took eight months.

**Comment by tjvr** [comment]
Haha! No, I understand completely. Life is like that :)

**Comment by nathan** [comment]
Soon ADPCM shall fall

**Comment by tjvr** [comment]
> the thirteen remaining pages of issues…

Ouch! :(

**Pull request closed without merging**
